// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthProvider string

const (
	AuthProviderGOOGLE      AuthProvider = "GOOGLE"
	AuthProviderGITHUB      AuthProvider = "GITHUB"
	AuthProviderCREDENTIALS AuthProvider = "CREDENTIALS"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider `json:"AuthProvider"`
	Valid        bool         `json:"valid"` // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type Assessment struct {
	ID             int32              `json:"id"`
	Userid         int32              `json:"userid"`
	Quizscore      float64            `json:"quizscore"`
	Questions      [][]byte           `json:"questions"`
	Category       string             `json:"category"`
	Improvementtip pgtype.Text        `json:"improvementtip"`
	Createdat      pgtype.Timestamptz `json:"createdat"`
	Updatedat      pgtype.Timestamptz `json:"updatedat"`
}

type CoverLetter struct {
	ID             int32              `json:"id"`
	Userid         int32              `json:"userid"`
	Content        string             `json:"content"`
	Jobdescription pgtype.Text        `json:"jobdescription"`
	Companyname    string             `json:"companyname"`
	Jobtitle       string             `json:"jobtitle"`
	Status         pgtype.Text        `json:"status"`
	Createdat      pgtype.Timestamptz `json:"createdat"`
	Updatedat      pgtype.Timestamptz `json:"updatedat"`
}

type IndustryInsight struct {
	ID                int32              `json:"id"`
	Industry          string             `json:"industry"`
	Salaryranges      [][]byte           `json:"salaryranges"`
	Growthrate        float64            `json:"growthrate"`
	Demandlevel       string             `json:"demandlevel"`
	Topskills         []string           `json:"topskills"`
	Marketoutlook     string             `json:"marketoutlook"`
	Keytrends         []string           `json:"keytrends"`
	Recommendedskills []string           `json:"recommendedskills"`
	Lastupdated       pgtype.Timestamptz `json:"lastupdated"`
	Nextupdate        pgtype.Timestamptz `json:"nextupdate"`
}

type MockInterviewAnswer struct {
	ID            int32              `json:"id"`
	Jsonmockresp  [][]byte           `json:"jsonmockresp"`
	Jobposition   string             `json:"jobposition"`
	Jobdesc       string             `json:"jobdesc"`
	Jobexperience string             `json:"jobexperience"`
	Mockid        string             `json:"mockid"`
	Question      string             `json:"question"`
	Correctans    pgtype.Text        `json:"correctans"`
	Userans       pgtype.Text        `json:"userans"`
	Feedback      pgtype.Text        `json:"feedback"`
	Rating        pgtype.Text        `json:"rating"`
	Userid        int32              `json:"userid"`
	Createdat     pgtype.Timestamptz `json:"createdat"`
}

type Resume struct {
	ID        int32              `json:"id"`
	Userid    int32              `json:"userid"`
	Content   string             `json:"content"`
	Atsscore  pgtype.Float8      `json:"atsscore"`
	Feedback  pgtype.Text        `json:"feedback"`
	Createdat pgtype.Timestamptz `json:"createdat"`
	Updatedat pgtype.Timestamptz `json:"updatedat"`
}

type User struct {
	ID                int32            `json:"id"`
	Email             string           `json:"email"`
	Password          pgtype.Text      `json:"password"`
	Name              string           `json:"name"`
	Imageurl          pgtype.Text      `json:"imageurl"`
	Industry          pgtype.Text      `json:"industry"`
	Bio               pgtype.Text      `json:"bio"`
	Experience        pgtype.Int4      `json:"experience"`
	Currentcv         pgtype.Text      `json:"currentcv"`
	Skills            []string         `json:"skills"`
	Linkedinprofile   pgtype.Text      `json:"linkedinprofile"`
	Github            pgtype.Text      `json:"github"`
	Provider          NullAuthProvider `json:"provider"`
	Provideraccountid pgtype.Text      `json:"provideraccountid"`
	Emailverified     pgtype.Bool      `json:"emailverified"`
}
