// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"
)

type Querier interface {
	CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	GetUserByProviderAccount(ctx context.Context, arg GetUserByProviderAccountParams) (User, error)
	UpdateUserEmailVerified(ctx context.Context, id int32) (User, error)
}

var _ Querier = (*Queries)(nil)
