// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthUser = `-- name: CreateOAuthUser :one
INSERT INTO "User" (
    name,
    email,
    imageUrl,
    provider,
    providerAccountId,
    emailVerified
)
VALUES ($1, $2, $3, $4, $5, true)
RETURNING id, email, password, name, imageurl, industry, bio, experience, currentcv, skills, linkedinprofile, github, provider, provideraccountid, emailverified, createdat, updatedat, lastlogin
`

type CreateOAuthUserParams struct {
	Name              string       `json:"name"`
	Email             string       `json:"email"`
	Imageurl          pgtype.Text  `json:"imageurl"`
	Provider          AuthProvider `json:"provider"`
	Provideraccountid pgtype.Text  `json:"provideraccountid"`
}

func (q *Queries) CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createOAuthUser,
		arg.Name,
		arg.Email,
		arg.Imageurl,
		arg.Provider,
		arg.Provideraccountid,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Imageurl,
		&i.Industry,
		&i.Bio,
		&i.Experience,
		&i.Currentcv,
		&i.Skills,
		&i.Linkedinprofile,
		&i.Github,
		&i.Provider,
		&i.Provideraccountid,
		&i.Emailverified,
		&i.Createdat,
		&i.Updatedat,
		&i.Lastlogin,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "User" (
    name,
    email,
    password,
    imageUrl
)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password, name, imageurl, industry, bio, experience, currentcv, skills, linkedinprofile, github, provider, provideraccountid, emailverified, createdat, updatedat, lastlogin
`

type CreateUserParams struct {
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Password pgtype.Text `json:"password"`
	Imageurl pgtype.Text `json:"imageurl"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Imageurl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Imageurl,
		&i.Industry,
		&i.Bio,
		&i.Experience,
		&i.Currentcv,
		&i.Skills,
		&i.Linkedinprofile,
		&i.Github,
		&i.Provider,
		&i.Provideraccountid,
		&i.Emailverified,
		&i.Createdat,
		&i.Updatedat,
		&i.Lastlogin,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, name, imageurl, industry, bio, experience, currentcv, skills, linkedinprofile, github, provider, provideraccountid, emailverified, createdat, updatedat, lastlogin
FROM "User"
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Imageurl,
		&i.Industry,
		&i.Bio,
		&i.Experience,
		&i.Currentcv,
		&i.Skills,
		&i.Linkedinprofile,
		&i.Github,
		&i.Provider,
		&i.Provideraccountid,
		&i.Emailverified,
		&i.Createdat,
		&i.Updatedat,
		&i.Lastlogin,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, password, name, imageurl, industry, bio, experience, currentcv, skills, linkedinprofile, github, provider, provideraccountid, emailverified, createdat, updatedat, lastlogin
FROM "User"
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Imageurl,
		&i.Industry,
		&i.Bio,
		&i.Experience,
		&i.Currentcv,
		&i.Skills,
		&i.Linkedinprofile,
		&i.Github,
		&i.Provider,
		&i.Provideraccountid,
		&i.Emailverified,
		&i.Createdat,
		&i.Updatedat,
		&i.Lastlogin,
	)
	return i, err
}

const getUserByProviderAccount = `-- name: GetUserByProviderAccount :one
SELECT id, email, password, name, imageurl, industry, bio, experience, currentcv, skills, linkedinprofile, github, provider, provideraccountid, emailverified, createdat, updatedat, lastlogin
FROM "User"
WHERE provider = $1
  AND providerAccountId = $2
`

type GetUserByProviderAccountParams struct {
	Provider          AuthProvider `json:"provider"`
	Provideraccountid pgtype.Text  `json:"provideraccountid"`
}

func (q *Queries) GetUserByProviderAccount(ctx context.Context, arg GetUserByProviderAccountParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByProviderAccount, arg.Provider, arg.Provideraccountid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Imageurl,
		&i.Industry,
		&i.Bio,
		&i.Experience,
		&i.Currentcv,
		&i.Skills,
		&i.Linkedinprofile,
		&i.Github,
		&i.Provider,
		&i.Provideraccountid,
		&i.Emailverified,
		&i.Createdat,
		&i.Updatedat,
		&i.Lastlogin,
	)
	return i, err
}

const updateUserEmailVerified = `-- name: UpdateUserEmailVerified :one
UPDATE "User"
SET emailVerified = true
WHERE id = $1
RETURNING id, email, password, name, imageurl, industry, bio, experience, currentcv, skills, linkedinprofile, github, provider, provideraccountid, emailverified, createdat, updatedat, lastlogin
`

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmailVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.Imageurl,
		&i.Industry,
		&i.Bio,
		&i.Experience,
		&i.Currentcv,
		&i.Skills,
		&i.Linkedinprofile,
		&i.Github,
		&i.Provider,
		&i.Provideraccountid,
		&i.Emailverified,
		&i.Createdat,
		&i.Updatedat,
		&i.Lastlogin,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :one
UPDATE "User"
SET lastLogin = now()
WHERE id = $1
RETURNING lastLogin
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int32) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, updateUserLastLogin, id)
	var lastlogin pgtype.Timestamptz
	err := row.Scan(&lastlogin)
	return lastlogin, err
}
